### ISSUE TITLE
Meta do we want a single file of projects?

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/GSoC#12]
- Seems like it will cause lots of merge conflicts
- We could just use issues; that's what I think I've seen other projects do?

**Comment by Janik-Haag** [comment]
> We could just use issues; that's what I think I've seen other projects do?

I tried to stick relatively close to: https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list
and it says:
> Never link to just a bug tracker. This is almost always an automatic rejection. Yes, really. When Admins open the issue tracker if there is an expanded description of the project with the items listed in #1 above that is acceptable. If an org can’t take the time to create a document or a page with their Ideas List fleshed out then why would Google expect they would be willing to mentor GSoC contributors for 3+ hours a week for the next 3+ months?

I guess having a separate repo that isn't just nix or nixpkgs doesn't count too much in this case.


> Seems like it will cause lots of merge conflicts

That's true, and I would have preferred to split it up into multiple files and then use some static site generator to render them back into one page, but we weren't able to set that up in time and had to link the idea list on the submit page.
Splitting the ideas up into multiple files and using github to view them would make it quite annoying to brows through the list since you would have to open 20 different tabs to view all of them.

**Comment by Ericson2314** [comment]
OK fair enough. I don't think the GitHub directory view is that bad, but GSoC does say "document or page" singular, so yeah the pressure is on.
